#PBS -N classify
#PBS -l select=1:ncpus=4:ngpus=2:mem=32gb:gpu_model=p100,walltime=24:00:00

cd /home/$USER/SciDAS/DeepGTEx
source activate gtex

	python scripts/classify.py --dataset ./data/float_data/panTCGA_gct_data_float_v1.npy \
						--gene_list ./data/gene_lists/gene_list_panTCGA_split.npy \
						--sample_json ./data/class_counts/panTCGA_tumor_count_v1.json \
						--subset_list ./subsets/ensg_hallmark_experiments.txt \
						--config ./models/net_config.json \
						--out_file ./logs/hallmark_classify_panTCGA.log
