#PBS -N classify
#PBS -l select=1:ncpus=4:ngpus=2:mem=8gb:gpu_model=p100,walltime=24:00:00

cd /home/$USER/SciDAS/gene-oracle
source activate tensorflow

	python scripts/classify.py --dataset ./panTCGA_data_v2/panTCGA_float_data_v2.npy \
						--gene_list ./panTCGA_data_v2/panTCGA_gene_lists_v2.npy \
						--sample_json ./panTCGA_data_v2/panTCGA_class_counts_v2.json \
						--random_test \
						--subset_list ./subsets/ensg_hallmark_experiments.txt \
						--config ./models/net_config.json \
						--rand_iters 50 \
						--out_file ./logs/hallmark_random_panTCGA_50iters_kfold10.log
