#PBS -N classify
#PBS -l select=1:ncpus=4:ngpus=2:mem=8gb:gpu_model=p100,walltime=24:00:00

cd /home/$USER/SciDAS/DeepGTEx
source activate gtex

	python scripts/classify.py --dataset ./data/float_data/gtex_gct_data_float_v7.npy \
						--gene_list ./data/gene_lists/gtex_gene_list_v7.npy \
						--sample_json ./data/class_counts/gtex_tissue_count_v7.json \
						--random_test \
						--subset_list ./subsets/hallmark_experiments.txt \
						--config ./models/net_config.json \
						--rand_iters 50 \
						--out_file ./logs/hallmark_random_50iters_kfold10.log
