#PBS -N mycv2panTCGA
#PBS -l select=1:ncpus=4:ngpus=2:mem=110gb:gpu_model=p100,walltime=72:00:00

cd /home/$USER/SciDAS/DeepGTEx
source activate gtex

        python scripts/subset_gene_test.py --dataset ./panTCGA_data_v2/panTCGA_float_data_v2.npy \
                                                --gene_list ./panTCGA_data_v2/panTCGA_gene_lists_v2.npy \
						--sample_json ./panTCGA_data_v2/panTCGA_class_counts_v2.json \
                                                --config ./models/net_config.json \
						--subset_list ./subsets/ensg_hallmark_experiments.txt \
						--set hallmark_myc_targets_v2 \
						--log_dir ./logs/hallmark_myc_targets_v2_panTCGA
