#PBS -N NOTCH_subset_test
#PBS -l select=1:ncpus=16:ngpus=2:mem=64gb:gpu_model=p100,walltime=72:00:00

cd /home/$USER/SciDAS/DeepGTEx
source activate gtex

	python scripts/subset_gene_test.py  --dataset ./data/float_data/gtex_gct_data_float_v7.npy \
							--gene_list ./data/gene_lists/gtex_gene_list_v7.npy \
							--sample_json ./data/class_counts/gtex_tissue_count_v7.json \
							--config ./models/net_config.json \
							--subset_list ./subsets/hallmark_experiments.txt \
							--set hallmark_notch_signaling \
							--num_genes 32 \
							--log_dir ./logs/hallmark_notch_signaling
