#PBS -N random43_pan
#PBS -l select=1:ncpus=4:ngpus=2:mem=96gb:gpu_model=p100,walltime=72:00:00

cd /home/$USER/SciDAS/gene-oracle
source activate tensorflow
        python scripts/gene-oracle.py --dataset ./panTCGA_data_v2/panTCGA_float_data_v2.npy \
                                                --gene_list ./panTCGA_data_v2/panTCGA_gene_lists_v2.npy \
						--sample_json ./panTCGA_data_v2/panTCGA_class_counts_v2.json \
                                                --config ./models/net_config.json \
                                                --set random${NUM} \
                                                --num_genes $GENE \
                                                --log_dir ./logs/random_${GENE}s_panTCGA/random${NUM}

