#PBS -N random_pan
#PBS -l select=1:ncpus=16:ngpus=2:mem=96gb:gpu_model=k40,walltime=72:00:00

cd /home/$USER/SciDAS/DeepGTEx
source activate gtex

	python scripts/subset_gene_test.py  --dataset ./data/float_data/panTCGA_gct_data_float_v1.npy \
							--gene_list ./data/gene_lists/gene_list_panTCGA_split.npy \
							--sample_json ./data/class_counts/panTCGA_tumor_count_v1.json \
							--config ./models/net_config.json \
							--set random$NUM \
							--num_genes 200 \
							--log_dir ./logs/random_200s_panTCGA/random$NUM
